steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Docker Build'
  args: ["build", "-t", "${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}", "."]
- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  entrypoint: gcloud
  args:
  - 'auth' 
  - 'configure-docker'
  - 'us-central1-docker.pkg.dev'
# - name: 'gcr.io/cloud-builders/docker'
#   args: ["docker", "run", "-dit", "--name", "apache_httpd_1", "-p", "8080:80", "us-central1-docker.pkg.dev/solution-kit-11/quickstart-docker-repo-pranav/apache_httpd"]
- name: "gcr.io/cloud-builders/kubectl"
  id: 'Push Image to Cluster'
  args:
  - 'run'
  - '--image'
  - 'us-central1-docker.pkg.dev/solution-kit-11/quickstart-docker-repo-pranav/apache_httpd'
  - 'apache-httpd-container'
  - '--'
  - 'bash'  
  env:
  - 'CLOUDSDK_COMPUTE_REGION=us-west1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=pranav-gke-cluster'
images:
- 'us-central1-docker.pkg.dev/solution-kit-11/quickstart-docker-repo-pranav/apache_httpd'
substitutions:
- _LOCATION:us-central1
- _REPOSITORY:quickstart-docker-repo-pranav
- _IMAGE:apache_httpd